In [ ]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

data = {
    "Age": [25, 30, 45, 35, 40, 28, 50, 23],
    "Salaire": [3000, 5000, 7000, 6000, 6500, 4000, 8000, 3200],
    "Anciennete": [1, 5, 10, 7, 8, 2, 15, 1],
    "Satisfaction": [4, 7, 6, 8, 5, 3, 9, 4],
    "HeuresSup": [20, 10, 5, 8, 12, 25, 3, 18],
    "Quiter": [1, 0, 0, 0, 1, 1, 0, 1]
}

df = pd.DataFrame(data)

print(df)

   Age  Salaire  Anciennete  Satisfaction  HeuresSup  Quiter
0   25     3000           1             4         20       1
1   30     5000           5             7         10       0
2   45     7000          10             6          5       0
3   35     6000           7             8          8       0
4   40     6500           8             5         12       1
5   28     4000           2             3         25       1
6   50     8000          15             9          3       0
7   23     3200           1             4         18       1


In [ ]:
X = df[["Age","Salaire","Anciennete","Satisfaction","HeuresSup"]]
Y = df["Quiter"]

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

# input_dim should only be specified in the first layer
model.add(Dense(10,activation="relu",input_dim=5))

model.add(Dense(5,activation="relu"))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer="adam",metrics=["accuracy"])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.fit(X,Y,epochs=5, batch_size=10)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 656.6967
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 647.2119
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 637.7672
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 628.3635
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 619.0016


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled X:\n", X_scaled[:5])

Scaled X:
 [[0.07407407 0.         0.         0.16666667 0.77272727]
 [0.25925926 0.4        0.28571429 0.66666667 0.31818182]
 [0.81481481 0.8        0.64285714 0.5        0.09090909]
 [0.44444444 0.6        0.42857143 0.83333333 0.22727273]
 [0.62962963 0.7        0.5        0.33333333 0.40909091]]


In [ ]:
model.fit(X_scaled, Y, epochs=100, batch_size=10)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 415ms/step - accuracy: 0.5000 - loss: 0.6444
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6443
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6441
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6439
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6436
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6434
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6432
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6430
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6428
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6426
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6423
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - l

In [ ]:
import numpy as np

nouvel_employe = np.array([[25,3200,1,4,18]])

prediction = model.predict(nouvel_employe)

print(prediction)

if prediction > 0.5:
    print("L'employé va quitter l'entreprise")
else:
    print("L'employé va rester")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.]]
L'employé va rester
